Repository selector-turing/back_end, pull requests merged in 2021-05, with the labels that each got.

#12 Graphql
  Gemfile
  Gemfile.lock
  app/assets/config/manifest.js
  app/controllers/api/v1/discogs_controller.rb
  app/controllers/graphql_controller.rb
  app/graphql/mutations/.keep
  app/graphql/mutations/base_mutation.rb
  app/graphql/selector_schema.rb
  app/graphql/types/.keep
  app/graphql/types/album_type.rb
  app/graphql/types/artist_type.rb
  app/graphql/types/base_argument.rb
  app/graphql/types/base_enum.rb
  app/graphql/types/base_field.rb
  app/graphql/types/base_input_object.rb
  app/graphql/types/base_interface.rb
  app/graphql/types/base_object.rb
  app/graphql/types/base_scalar.rb
  app/graphql/types/base_union.rb
  app/graphql/types/images_type.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/query_type.rb
  app/graphql/types/tracklist_type.rb
  app/models/album.rb
  app/poros/album.rb
  app/services/discogs_service.rb
  config/application.rb
  config/routes.rb
  db/migrate/20210515163346_create_albums.rb
  db/schema.rb
  spec/models/album_spec.rb
Labels: BE

#14 Refactor
  config/application.rb
Labels: BE

#16 Travis ci
  .travis.yml
  Gemfile.lock
  app/assets/config/manifest.js
  spec/cassettes/Discogs_API_request/Returns_realease_data_for_album_query_params_from_user.yml
  spec/requests/api/v1/discogs_request_spec.rb
Labels: BE, Sprint #1

#17 Add filter sensitive data for discogs key
  app/services/discogs_service.rb
  spec/rails_helper.rb
Labels: BE, sprint #2

#21 Spotify album
  spec/cassettes/Spotify_API_request/Returns_realease_data_for_album_query_params_from_user.yml
  spec/graphql/spotify_spec.rb
Labels: BE, sprint #2

#22 Album
  app/assets/config/manifest.js
  app/graphql/types/query_type.rb
  app/services/spotify_service.rb
  spec/graphql/spotify_spec.rb
Labels: BE, sprint #2

#23 Add re-comment for manifest.js file
  app/assets/config/manifest.js
Labels: BE, sprint #2

#24 Testing
  app/controllers/application_controller.rb
  app/graphql/selector_schema.rb
  app/graphql/types/album_type.rb
  app/graphql/types/tracklist_type.rb
  app/services/discogs_service.rb
  app/services/spotify_service.rb
  config/initializers/execution_error.rb
  spec/graphql/discogs_spec.rb
  spec/graphql/queries/discogs_spec.rb
  spec/graphql/queries/spotify_spec.rb
  spec/graphql/spotify_spec.rb
  spec/requests/api/v1/discogs_request_spec.rb
Labels: BE, sprint #2

#28 Artist albums
  app/services/discogs_service.rb
  spec/graphql/queries/discogs_spec.rb
Labels: BE

#30 Find albums by artists
  app/graphql/types/artist_albums_type.rb
  app/graphql/types/query_type.rb
  app/services/discogs_service.rb
  spec/cassettes/Discogs_API_request/Happy_Paths/Returns_release_data_for_album_query_params_from_user.yml
  spec/cassettes/Discogs_API_request/Sad_Paths/Returns_error_for_blank_release_data_album_query_params_from_user.yml
  spec/cassettes/Discogs_API_request/Sad_Paths/Returns_error_for_gibberish_release_data_album_query_params_from_user.yml
  spec/graphql/queries/discogs_spec.rb
  spec/services/discogs_services_spec.rb
Labels: BE

#32 Adds CORS
  config/initializers/cors.rb
Labels: BE

#33 Adds database and modifications for random album
  app/graphql/mutations/create_album.rb
  app/graphql/types/mutation_type.rb
  app/models/favorite.rb
  app/services/discogs_service.rb
  app/services/spotify_service.rb
  db/migrate/20210524202256_create_favorites.rb
  db/schema.rb
  spec/cassettes/Discogs_API_request/Happy_Paths/Returns_artist_and_the_first_10_of_their_albums.yml
  spec/cassettes/Discogs_API_request/Happy_Paths/Returns_release_data_for_a_random_album.yml
  spec/cassettes/Discogs_API_request/Happy_Paths/Returns_release_data_for_album_query_params_from_user.yml
  spec/cassettes/Discogs_API_request/Sad_Paths/Returns_error_for_blank_release_data_album_query_params_from_user.yml
  spec/cassettes/Discogs_API_request/Sad_Paths/Returns_error_for_gibberish_release_data_album_query_params_from_user.yml
  spec/cassettes/Types_QueryType/Sad_Paths/Returns_error_when_a_one_space_search_title_is_given.yml
  spec/cassettes/Types_QueryType/Sad_Paths/Returns_error_when_blank_search_title_is_given.yml
  spec/cassettes/Types_QueryType/Sad_Paths/Returns_error_when_invalid_search_title_is_given.yml
  spec/cassettes/Types_QueryType/Spotify_API_request/Returns_Album_ID_for_album_query_params_from_user.yml
  spec/graphql/queries/discogs_spec.rb
  spec/models/favorite_spec.rb
Labels: BE
